### ISSUE TITLE
[BUG]latest cmd/micro can't use plugins

### ISSUE THREAD

**Issue by bootfirst** [go-micro/go-micro#2335]
**Describe the bug**

```bash
micro --registry etcd services
```
can't get the right response

I add the plugins:
```go
_ "github.com/asim/go-micro/plugins/registry/etcd/v4"

```
ADDITIONALLY add cmd/micro/cli/cli.go:112
```go
c.app.Before = mcmd.DefaultCmd.App().Before
```
and get the right response.

So can the 'micro' command be ready with the common plugins?

**Comment by AuditeMarlow** [comment]
Unfortunately the Micro CLI does not support plugins and most likely will not support plugins in the near future due to the nature of how plugins are set up in go-micro.

If we want the Micro CLI to support plugins, we'd either have to load all currently available and future plugins in the Micro CLI binary, or we'd have to rethink go-micro's plugin ecosystem. The former isn't a feasible solution in my opinion as the Micro CLI would effectively become large in size and be bloated by tons of plugins most users wouldn't be using. The latter might be a feasible solution but I have no idea where to even begin at this time.

**Comment by bootfirst** [comment]
Thank you for your kind response.
If we can easily build a 'micro cli' with chosen plugins, that's also a solution with plugin philosophy.
For example, simply add
```go
_ "github.com/asim/go-micro/plugins/registry/etcd/v4"
```
to xxx/xxx/plugins.go and `go build .`
