### ISSUE TITLE
`NewService` vs `srv.Init`

### ISSUE THREAD

**Issue by Davincible** [go-micro/go-micro#2560]
@asim 

Currently, it's a convention to first create a new service with `micro.NewService` and to subsequently call `srv.Init`.

However, the only difference between the two is that the latter calls the cmd package to init envs etc, while the former doesn't. 

Thus I'm wondering if there's any reason to keep the two (apart from backwards compatibility)? The only 'upside' to `Init` is that you can create a service without calling `cmd.Init`, which I don't think is necessary as there is no downside to always calling `cmd.Init` (right?)

I'm wondering because we could just as well do the `cmd.Init` in the `NewService` eliminating the need for the call to `srv.Init`, right?

**Comment by asim** [comment]
So there's a few reasons why it was implemented this way. The first, someone may not actually want to call cmd.Init e.g they want to use the "flag" package rather than the built in flags and env parsing. The second, There are certain values that may depend on having the service instance, the only way to provide this to them is in some sort of AfterFunc which gets called after the service has initialised everything.

Those two points aside, personally I think whatever is the simplest solution is the one you should carry forward, that may be as you said, to just call cmd.Init in NewService and let people use individual packages otherwise if they don't want that. I will leave the decision to you.

**Comment by jochumdev** [comment]
I realy need service := micro.NewService() -> service.Init() cause i need `service` in micro.Action()

See: 
https://git.jochum.dev/jo-micro/settings/src/branch/main/cmd/microsettingsd/main.go#L35

**Comment by Davincible** [comment]
I see, I will leave it as is then.

@pcdummy I was only suggesting to (also) call `cmd.Init` in `NewService` so it's not necessary to call `Init` to use envs. But won't change that.
