### ISSUE TITLE
grpc stream use async socket send, but seem use them same buffer, the newer msg seems overwrite the underlying buffer

### ISSUE THREAD

**Issue by dashessmith** [go-micro/go-micro#2671]
![image](https://github.com/go-micro/go-micro/assets/75690316/ee3ffd96-167b-4fb9-b51f-cb1dfa7e0787)

**Comment by dashessmith** [comment]
![image](https://github.com/go-micro/go-micro/assets/75690316/5bc353ee-b666-4035-867a-02907fa7c130)

this bytes.buffer seems not thread safe

**Comment by DingYuan0118** [comment]
Encounter the same problem. Use grpc server seems to avoid this

**Comment by DingYuan0118** [comment]
<img width="894" alt="image" src="https://github.com/go-micro/go-micro/assets/42141845/622dadc9-281d-4eff-9262-7f54d58e3d1a">
Seems all buf in channel use the same pointer which point to the underlying []byte since buf.Reset() does not change buf's address buf.Bytes() always return the same pointer. 

use `copy()` to make a new []byte and then put it into channel can solve this.

```go
func TestBuffer(t *testing.T) {
	wg := sync.WaitGroup{}
	defer wg.Wait()

	var ch = make(chan []byte, 128)
	wg.Add(1)
	go func() {
		defer wg.Done()

		buf := bytes.Buffer{}

		defer close(ch)

		for i := 1; i < 10; i++ {
			buf.Write([]byte(fmt.Sprintf("%v", i)))
			bs := buf.Bytes()
			buf.Reset()
			b := make([]byte, len(bs))
			copy(b, bs)
			ch <- b
		}

	}()

	wg.Add(1)

	go func() {
		defer wg.Done()
		for x := range ch {
			fmt.Printf("i:=%v\n", string(x))
		}
	}()
}


i:=1
i:=2
i:=3
i:=4
i:=5
i:=6
i:=7
i:=8
i:=9
```

**Comment by DingYuan0118** [comment]
<img width="639" alt="image" src="https://github.com/go-micro/go-micro/assets/42141845/9f77b4d7-1432-4845-8970-b4efa736cc41">

Change like this seems to make it work normal.
